### ISSUE TITLE
add automated tests for notebooks 

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/example-notebooks#13]

**Comment by iishiishii** [comment]
we can render them in documentation? https://jupyterbook.org/en/stable/start/build.html

**Comment by iishiishii** [comment]
and simple test run with https://github.com/marketplace/actions/nbmake

**Comment by stebo85** [comment]
that would be cool :)

**Comment by iishiishii** [comment]
Apparently, it was not because of the path but Github action runs out of memory for the job that actually caused the error https://iishiishii.github.io/example-notebooks/structural_imaging/qsmxt_example.html#segment-t1-weighted-images

**Comment by stebo85** [comment]
that makes sense - this job is quite memory intense. Should we run these jobs on our larger custom runners? I can set this up if you like :)

**Comment by iishiishii** [comment]
only 1 workflow in qsmxt example failed for that error, other examples seem to be alright, but that would be easier to test. Thank you!

**Comment by stebo85** [comment]
Wonderful work on this Thuy :)
